### ISSUE TITLE
influxdb address using hostname is not supported

### ISSUE THREAD

**Issue by firesh** [p0pr0ck5/lua-resty-influx#3] opened 2017-06-22 17:57 UTC
I can ping with hostname "influxdb" from my openresty server, but if i configure host with hostname, it won't  be success to write any data. If configure host with IP address, it works well.

`local ok, err = ibuf.init({
                        host = "influxdb",
                        port = 8086,
                        proto = "http",
                        db = "access",
                })
`

**Comment by p0pr0ck5** [comment] 2017-06-22 17:58
Is that hostname resolvable through your configured DNS resolver?

This isn't a bug with this lib, this is just a matter of configuring DNS properly for this hostname.

**Comment by firesh** [comment] 2017-06-22 18:01
Ping is ok. This hostname is configured in `/etc/hosts`.
`/ # ping influxdb
PING influxdb (192.168.0.23): 56 data bytes
64 bytes from 192.168.0.23: seq=0 ttl=64 time=0.201 ms
64 bytes from 192.168.0.23: seq=1 ttl=64 time=0.128 ms
64 bytes from 192.168.0.23: seq=2 ttl=64 time=0.119 ms
64 bytes from 192.168.0.23: seq=3 ttl=64 time=0.120 ms
^C
--- influxdb ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 0.119/0.142/0.201 ms`

**Comment by p0pr0ck5** [comment] 2017-06-22 18:03
I don't know if OpenResty uses hostnames in /etc/resov.conf. Again, this is an openresty thing, not this library in particular

**Comment by firesh** [comment] 2017-06-22 18:12
It is caused by resty.http module bug.
refer: https://github.com/pintsized/lua-resty-http/pull/95

**Comment by p0pr0ck5** [comment] 2017-06-22 18:15
This was not a bug:

> It doesn't make sense to me to add this to lua-resty-http. If you wish to resolve host names to IP addresses in a custom way, you're free to do that, and then connect to the IP manually and use the request() method.
> 
> If you really need /etc/hosts to be utilised automatically, surely a better way is to use something like dnsmasq as a local resolver, and tell Nginx to use this with the resolver directive?

> If this method of auto resolution (i.e. not using the Nginx resolver) should be considered a better standard way of working, I'd suggest raising it for discussion more widely on the OpenResty mailing list, because it should affect all cosocket modules really. It doesn't make sense to bury this within just the HTTP driver specifically.

If you really want to use /etc/resolv.conf, you could try looking at https://github.com/Mashape/lua-resty-dns-client.

This, however, is not a bug with lua-resty-influx. Closing this.

**Closed as completed by p0pr0ck5** 2017-06-22 18:15 UTC
